### ISSUE TITLE
Application Form 

### ISSUE THREAD

**Issue by Ahmed-Khaled24** [ASU-Semicolon/Semicolon-landing-page#28]
# Application page improvement
instead of a central form without title we need to upgrade to use something like the provided image below, the form is the page with a title relative to the current event the applicant applies for
![image](https://github.com/ASU-Semicolon/Semicolon-landing-page/assets/80486237/4adcc111-e6e4-4682-a059-ea639bf84e44)
![image](https://github.com/ASU-Semicolon/Semicolon-landing-page/assets/80486237/db2220f5-069a-400f-85eb-10541f873dea)

**Comment by balbal1** [comment]
So just make a separate route for each form and customize the fields for each event? So what does the image provide?

**Comment by Ahmed-Khaled24** [comment]
We may create a single page component with a dynamic title passed as a prop.
We don't have different forms it is the same form but for different purposes, we use it once for member recruitment and once for workshop students.

**Comment by balbal1** [comment]
So the prop will choose which backend endpoint the form will submit to?

**Comment by balbal1** [comment]
Done. now the prop changes the dropdown list of committees of workshops to apply on. the backend endpoint is kept the same for now until the new backend gets deployed.
